/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.15.4.0 (NJsonSchema v9.10.29.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { NgModule } from '@angular/core';

import * as clients from './clients';

const _CLIENTS = [
	clients.AccountClient,
	clients.ConfigurationClient,
	clients.ProductServiceClient,
	clients.RoleClient,
	clients.SessionClient,
	clients.TenantClient,
	clients.TokenAuthClient,
	clients.UserClient,
];

@NgModule({
    providers: [..._CLIENTS],
})
export class AbpServiceModule { }
